# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {
#         "text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.",
#         "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
#      "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

Geography_Question = [{
    "question": "A group of islands is called an archipelago.",
    "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Greenland is covered with grass and Iceland covered with ice.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "The Republic of Malta is the smallest microstate worldwide.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Vatican City is a country.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "There is a city called Rome in every continent on Earth.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Ottawa is the capital of Canada.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Tokyo is the capital of Japan.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Hungary is the only country in the world beginning with H.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "Nova Scotia is on the east coast of Canada.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "There is an island in Japan called kunoshima, A.K.A. 'Rabbit Island';, so named because of it is huge population of rabbits.",
     "correct_answer": "True", "incorrect_answers": ["False"]
     }
]

Gk_Question = [{"question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                  "question": "Nutella is produced by the German company Ferrero.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                  "question": "Bulls are attracted to the color red.", "correct_answer": "False",
                                  "incorrect_answers": ["True"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                  "question": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                  "question": "The Sun rises from the North.", "correct_answer": "False",
                                  "incorrect_answers": ["True"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                  "question": "You can legally drink alcohol while driving in Mississippi.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                  "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                                  "incorrect_answers": ["False"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                  "question": "Scotland voted to become an independent country during the referendum from September 2014.",
                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                  "question": "The National Animal of Scotland is the Unicorn.",
                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                  "question": "Slovakia is a member of European Union-", "correct_answer": "True",
                                  "incorrect_answers": ["False"]}]
